displayName=Potion Boosts
author=javlanoob
support=https://github.com/javlanoob/potion-boosts
description=Shows what a potion would boost on the potion itself
tags=potion,boost,level,skill,stat,inventory,icons
plugins=com.potionboosts.PotionBoostsPlugin
version=1.0
build=standard
